
CREATE TABLE IF NOT EXISTS password_reset (
	ID SERIAL PRIMARY KEY,
	EMAIL VARCHAR(200) NOT NULL,
	OTP VARCHAR(6) NOT NULL,
	CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	EXPIRES_AT TIMESTAMP NOT NULL,
    resend_available_at TIMESTAMP
);
